//
// Created by douwe on 20-11-18.
//

#ifndef SMOOTHPARTICLEHYDRODYNAMICS_DYNAMIC_ARRAY_H
#define SMOOTHPARTICLEHYDRODYNAMICS_DYNAMIC_ARRAY_H
    int* alloc_array(int n);
#endif //SMOOTHPARTICLEHYDRODYNAMICS_DYNAMIC_ARRAY_H
