#ifndef SMOOTHPARTICLEHYDRODYNAMICS_SMOOTING_FUNCTION_H
#define SMOOTHPARTICLEHYDRODYNAMICS_SMOOTING_FUNCTION_H

#include "particle.h"

double smoothing_funtion(particle particle1, particle particle2, int h);

#endif //SMOOTHPARTICLEHYDRODYNAMICS_SMOOTING_FUNCTION_H
